#pragma once

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define WELCOME_SCREEN_RED 0
#define WELCOME_SCREEN_GREEN 0
#define WELCOME_SCREEN_BLUE 255
#define WELCOME_SCREEN_OPACITY 255

#define DEFAULT_OBJECT_RED 0
#define DEFAULT_OBJECT_GREEN 0
#define DEFAULT_OBJECT_BLUE 0
#define DEFAULT_OBJECT_VELOCITY 0
#define DEFAULT_OBJECT_POSITION 0
#define DEFAULT_OBJECT_X_ACCELERATION 0
#define GRAVITY_ACCELERATION 9.8
#define DEFAULT_OBJECT_SIZE 0
