#pragma once

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define WELCOME_SCREEN_RED 0
#define WELCOME_SCREEN_GREEN 0
#define WELCOME_SCREEN_BLUE 255
#define WELCOME_SCREEN_OPACITY 255

#define GRAVITY_ACCELERATION 9.8