name: checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install \
            build-essential \
            x11-apps \
            libsdl2-2.0-0 \
            libsdl2-dev \
            libsdl2-image-2.0-0 \
            libsdl2-image-dev \
            libzmq3-dev \
            cmake \
            clang-format \
            clang-tidy

    - name: Check build
      run: make

    - name: Check formatting
      run: make check-format

    - name: Run linter
      run: make check-tidy
