name: checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            x11-apps \
            cmake \
            ninja-build \
            clang-format \
            clang-tidy

    - name: Configure build
      run: make configure

    - name: Check build
      run: make

    - name: Check formatting
      run: make check-format

    - name: Run linter
      run: make check-tidy
